### ISSUE TITLE
Build on CI fails

### ISSUE THREAD

**Issue by artmees** [clutchski/coffeelint#385]
I'm using Wercker as a CI platform...
while installing the `gulp-coffeelint` which installs `coffeelint` as dependency... it fails on wercker returning the following error

```
Modules/coffeelint
> cake install

module.js:340
    throw err;

Error: Cannot find module 'browserify'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
...
Error: Cannot find module 'module-deps'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:1:75)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
....
Error: Cannot find module 'deps-sort'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:2:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
....
Error: Cannot find module 'browser-pack'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:3:13)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
....
Error: Cannot find module 'insert-module-globals'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:4:21)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
....
Error: Cannot find module 'syntax-error'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:5:19)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
....
Error: Cannot find module 'assert/'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.require.resolve (module.js:384:19)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/lib/builtins.js:1:88)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:7:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
....
Error: Cannot find module 'buffer/'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.require.resolve (module.js:384:19)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/lib/builtins.js:2:26)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:7:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
...
npm ERR! coffeelint@1.9.1 install: `cake install`
npm ERR! Exit status 8

```
I added the `browserify`, `module-deps`, `deps-sort`, `browser-pack`, `insert-module-globals`, `syntax-error`, `assert` dependency manually to my `package.json` in order for the `npm install` to succeed (one at a time :tired_face: )...

after showing the last error about missing `buffer` I lost hope and went back for using `~1.8.1` instead of `^1.9.1` (which builds correctly without adding any dependency)

node v0.10.35
npm v2.1.8

**Comment by AsaAyers** [comment]
Are you able to install coffeelint 1.9.1 and run the commandline manually? Not saying it's a solution, just trying to work out what's going on. I've never heard of Wercker  and don't use gulp.

**Comment by artmees** [comment]
wercker creates a VM and install the package.json dependencies... but due to it's nature and security... all of the dependencies must be specified... cause internally it can't use `npm -g` only `npm install` and It has to find the dependencies in the `VM/build/SOMEKEY/project_dir/node_modules/` otherwise it can't access any other directory than the `project_dir`... so the problem is that it can't find those specified node modules in the dependencies...

and I can't ssh into it... I'm not in a hurray for updating to 1.9.1... but I find the fact that those dependencies are not stated is **disturbing**... :smile:

**Comment by AsaAyers** [comment]
Those are not a dependency when installing from npm. I think wecker is doing something wrong. It sounds like it's running "npm install" from inside the coffeelint checkout, which is only needed if you're actually developing for CoffeeLint. The version published to npm is pre-compiled.

**Comment by AsaAyers** [comment]
I'm still confused as to how 1.8 works for you but 1.9.1 doesn't. Does 1.9.0 work?

**Comment by artmees** [comment]
1.8.1 works
1.9.1 doesn't

yeah it builds **some** modules from the source... I don't know which modules exactly but I've made sure that the problem was running `cake install` inside `node_modules/coffeelint` when it was `1.9.1` but it didn't try to build `1.8.1` :weird:

here is the logs for npm install when `1.8.1`
```
coffeelint@1.8.1 node_modules/coffeelint
├── ignore@2.2.15
├── resolve@0.6.3
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@4.4.0 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
└── coffee-script@1.7.1 (mkdirp@0.3.5)
```
while when 1.9.1
```
 odules/coffeelint
> cake install

\odule.js:340
    throw err;
          ^
Error: Cannot find module 'buffer/'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.require.resolve (module.js:384:19)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/lib/builtins.js:2:26)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/browserify/index.js:7:16)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (/pipeline/build/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:10:16)
  at Object.<anonymous> (/pipeline/build/node_modules/coffeelint/Cakefile:90:4)
  at Module._compile (module.js:456:26)
`linux-x64-node-0.10` exists; testing
Binary is fine; exiting
npm ERR! Linux 3.2.0-54-virtual
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.10.35
npm ERR! npm  v2.6.0
npm ERR! code ELIFECYCLE

npm ERR! coffeelint@1.9.1 install: `cake install`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the coffeelint@1.9.1 install script 'cake install'.
npm ERR! This is most likely a problem with the coffeelint package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cake install
npm ERR! You can get their info via:
npm ERR!     npm owner ls coffeelint
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /pipeline/build/npm-debug.log
```

**Comment by artmees** [comment]
1.9.0 works fine from precompiled and doesn't also require to build
```
coffeelint@1.9.0 node_modules/coffeelint
├── ignore@2.2.15
├── resolve@0.6.3
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
└── glob@4.4.0 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
```

**Comment by AsaAyers** [comment]
ok, I think I borked my release of 1.9.1 last night. I just pushed 1.9.2. I'm confident that it will fix it, as I just installed it locally and saw the correct change in package.json.

From my [release docs](https://github.com/clutchski/coffeelint/blob/master/doc/release.md)

> I think it's important that people be able to install CoffeeLint directly from git. People also got upset when the NPM version required installing browserify and coffeeify when they were never actually used. For this reason I have a prepublish script that will yank those and the install script out of package.json. I had this fail to run for me once, so now I run it manually just to make sure it's fine before I publish.

I don't know how, but it looks like 1.9.1 had the `scripts.install` key present that runs cake, but didn't have the browserify and coffeeify.

**Comment by AsaAyers** [comment]
Sorry for causing trouble. I just don't have a better solution yet that satisfies:

* Must be able to install from GIT
* Must be able to install from npm
* Must NOT ship browserify/coffeeify when installing pre-compiled from npm

**Comment by artmees** [comment]
1.9.2 works fine :tophat: :+1: :clap: :you_are_awesome: :wink:
