### ISSUE TITLE
CoffeeScript v2

### ISSUE THREAD

**Issue by boris-petrov** [clutchski/coffeelint#595]
[CoffeeScript 2 is coming!](http://coffeescript.org/v2/#changelog) I'm reading that this project here is almost abandoned. I *completely* do not agree that CoffeeScript is dead and should be replaced by ES2015. CS is still a much more beautiful language, is easier to write and I personally have no intention of switching over to JS any time soon. I'm absolutely sure that I'm not alone in my thinking.

Are we going to see new releases for CoffeeLint (e.g. working with the new things in CoffeeScript 2, bugfixes, etc) or is this project practically dead?

**Comment by swang** [comment]
Hey.

Sorry for the late reply. I have been taking a break from working on stuff on github since the beginning of the year.

I have always been accepting bugfixes, I just haven't really received many recently. 

I took a look at v2 and what I thought would maybe take an hour has taken up my entire night to fix all the little problems v2 has.

Personally for me at the moment I probably won't have time to add new features once version 2 comes around. I will push my fixes for cs2 (I found an issue with cs2 while testing) but I think if people want further changes someone is probably going to have to step in and help out.

**Comment by boris-petrov** [comment]
Hi!

No worries, thanks for the reply!

My case in point was that CoffeeScript is far from dead and CoffeeLint is a beautiful project which many people use and will continue to use after CS v2 is out. Please don't kill it. :) Just wanted to point that out.

You could put it in the README that you're looking for help/contributors/maintainers/etc. Hopefully someday someone will come along.

Thanks for the time you're spending on CoffeeLint!

**Comment by boris-petrov** [comment]
@swang - I tried using your branch `cs2` in my `package.json` but I'm getting an error during `npm install`:

```
> coffeelint@1.16.0 install /home/boris/code/project/frontend/node_modules/coffeelint
> cake install

Compiling Coffeelint...
fs.js:653
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'src/commandline.coffee'
    at Object.fs.openSync (fs.js:653:18)
    at Object.fs.readFileSync (fs.js:554:33)
    at coffeeSync (/home/boris/code/project/frontend/node_modules/coffeelint/Cakefile:22:17)
    at Object.action (/home/boris/code/project/frontend/node_modules/coffeelint/Cakefile:37:5)
    at invoke (/home/boris/code/project/frontend/node_modules/coffeescript/lib/coffeescript/cake.js:57:26)
    at Object.action (/home/boris/code/project/frontend/node_modules/coffeelint/Cakefile:32:12)
    at invoke (/home/boris/code/project/frontend/node_modules/coffeescript/lib/coffeescript/cake.js:57:26)
    at Object.action (/home/boris/code/project/frontend/node_modules/coffeelint/Cakefile:98:14)
    at invoke (/home/boris/code/project/frontend/node_modules/coffeescript/lib/coffeescript/cake.js:57:26)
    at Object.exports.run (/home/boris/code/project/frontend/node_modules/coffeescript/lib/coffeescript/cake.js:87:20)
    at Object.<anonymous> (/home/boris/code/project/frontend/node_modules/coffeescript/bin/cake:15:42)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:201:16)
    at bootstrap_node.js:626:3
```

How do I fix this?

**Comment by danielbayley** [comment]
@boris-petrov I'm using a local clone and `npm link` which isn't ideal, but does work until #596 goes through (hopefully soon).
